# .github/workflows/product_sync.yml
name: Product Sync

on:
  workflow_dispatch:

concurrency:
  group: database-operations
  cancel-in-progress: false

jobs:
  sync_products:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run product sync
        env:
          XT_XARID_LOGIN: ${{ secrets.XT_XARID_LOGIN }}
          XT_XARID_PASSWORD: ${{ secrets.XT_XARID_PASSWORD }}
          MYSQL_DB: ${{ secrets.MYSQL_DB }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_SSL_CA: ${{ secrets.MYSQL_SSL_CA }}
          MYSQL_SSL_CERT: ${{ secrets.MYSQL_SSL_CERT }}
          MYSQL_SSL_KEY: ${{ secrets.MYSQL_SSL_KEY }}
          MYSQL_SSL_VERIFY_CERT: ${{ secrets.MYSQL_SSL_VERIFY_CERT }}
          MYSQL_SSL_VERIFY_IDENTITY: ${{ secrets.MYSQL_SSL_VERIFY_IDENTITY }}
        run: |
          python create_products/product_sync.py

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-sync: Product sync completed $(date '+%Y-%m-%d %H:%M:%S')"
          git pull origin main
          git push

      # Database is now stored in MySQL server, no need to upload artifacts
