# .github/workflows/scraper.yml
name: Scraper

on:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install requests peewee

      - name: Run scraper
        run: |
          cd scapper
          python scraper.py

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-update: Scraped data $(date '+%Y-%m-%d %H:%M:%S')"
          git push

      - name: Upload database as artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraper-database
          path: scapper/data/scraper.db
          retention-days: 30
